server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:file:./data/accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console  # ⬅️ Console URL: http://localhost:8089/h2-console

  application:
    name: account-management-service

six_bank:
  account:
    prefix: SIX

account:
  api:
    version: v1.0


